# Generated by Django 4.2.7 on 2023-11-12 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="наименование"),
                ),
                ("description", models.TextField(verbose_name="описание")),
                ("price", models.IntegerField(verbose_name="цен")),
                ("phone", models.TextField(verbose_name="номер телефона")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="активность объявления"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="время создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ("-is_active", "-date_time"),
            },
        ),
    ]
