# Generated by Django 4.2.7 on 2023-11-15 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.IntegerField(verbose_name="цена"),
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="наименование"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание")),
                ("budget", models.IntegerField(verbose_name="бюджет")),
                (
                    "avatar",
                    models.ImageField(
                        default="uploads/ideas/default.jpg",
                        upload_to="uploads/ideas/avatar/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "bmp"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "additional",
                    models.FileField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        upload_to="uploads/ideas/additional/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "docs", "doc"]
                            )
                        ],
                        verbose_name="Дополнительный файл",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="активность объявления"
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="время создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Идея",
                "verbose_name_plural": "Идеи",
                "ordering": ("-is_active", "-date_time"),
            },
        ),
    ]
