# Generated by Django 4.2.7 on 2023-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="author",
            field=models.CharField(max_length=300, verbose_name="Автор"),
        ),
    ]
