# Generated by Django 4.2.7 on 2023-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_alter_service_price_idea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="наименование"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="цена")),
            ],
            options={
                "verbose_name": "Расценка",
                "verbose_name_plural": "Расценки",
                "ordering": ("price", "title"),
            },
        ),
    ]
